### ISSUE TITLE
SimpleRelay problem on and off

### ISSUE THREAD

**Issue by lokanath467** [JSC-electronics/Relay#1]
Actually relay.on() is turning off and relay.off() is turning on. Please check.

**Comment by lokanath467** [comment]
I found in your implementation you are using isInverted=false. It is working properly when isInverted=True, Please change default value to true otherwise function names lose significance.

**Comment by Ales-Svoboda** [comment]
Hello lokanath467, this actually depends on your HW configuration (what type of relay/module you use in your project). You can also use constructor `SimpleRelay relay = SimpleRelay(RELAY_PIN, true);`, which causes the logic will be inverted.

By default, relay.on() sets log. 1 on the given output, which is more intuitive.
